title: "Velvet Afterthoughts"
description: "A digital space to weave together my thoughts on life, style, values, and the art of being."
theme: minima
plugins_dir: jekyll-feed
header_pages: subscribe.md
github_subscribe_token: YOUR_TOKEN_HERE
