title: "Velvet Afterthoughts"
description: "A digital space to weave together my thoughts on life, style, values, and the art of being."
theme: minima
plugins:
  - jekyll-feed
header_pages: subscribe.md
